/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard.analytics'
import { Route as DashboardClientsRouteImport } from './routes/_dashboard.clients'
import { Route as DashboardContentRouteImport } from './routes/_dashboard.content'
import { Route as DashboardIntegrationsRouteImport } from './routes/_dashboard.integrations'
import { Route as DashboardLeadsRouteImport } from './routes/_dashboard.leads'
import { Route as DashboardLinkedinRouteImport } from './routes/_dashboard.linkedin'
import { Route as DashboardOutreachRouteImport } from './routes/_dashboard.outreach'
import { Route as DashboardReportsRouteImport } from './routes/_dashboard.reports'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardTasksRouteImport } from './routes/_dashboard.tasks'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinkedinRoute = DashboardLinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOutreachRoute = DashboardOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/clients': typeof DashboardClientsRoute
  '/content': typeof DashboardContentRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/leads': typeof DashboardLeadsRoute
  '/linkedin': typeof DashboardLinkedinRoute
  '/outreach': typeof DashboardOutreachRoute
  '/reports': typeof DashboardReportsRoute
  '/settings': typeof DashboardSettingsRoute
  '/tasks': typeof DashboardTasksRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/clients': typeof DashboardClientsRoute
  '/content': typeof DashboardContentRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/leads': typeof DashboardLeadsRoute
  '/linkedin': typeof DashboardLinkedinRoute
  '/outreach': typeof DashboardOutreachRoute
  '/reports': typeof DashboardReportsRoute
  '/settings': typeof DashboardSettingsRoute
  '/tasks': typeof DashboardTasksRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/_dashboard/clients': typeof DashboardClientsRoute
  '/_dashboard/content': typeof DashboardContentRoute
  '/_dashboard/integrations': typeof DashboardIntegrationsRoute
  '/_dashboard/leads': typeof DashboardLeadsRoute
  '/_dashboard/linkedin': typeof DashboardLinkedinRoute
  '/_dashboard/outreach': typeof DashboardOutreachRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/tasks': typeof DashboardTasksRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/clients'
    | '/content'
    | '/integrations'
    | '/leads'
    | '/linkedin'
    | '/outreach'
    | '/reports'
    | '/settings'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/clients'
    | '/content'
    | '/integrations'
    | '/leads'
    | '/linkedin'
    | '/outreach'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/analytics'
    | '/_dashboard/clients'
    | '/_dashboard/content'
    | '/_dashboard/integrations'
    | '/_dashboard/leads'
    | '/_dashboard/linkedin'
    | '/_dashboard/outreach'
    | '/_dashboard/reports'
    | '/_dashboard/settings'
    | '/_dashboard/tasks'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clients': {
      id: '/_dashboard/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content': {
      id: '/_dashboard/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/integrations': {
      id: '/_dashboard/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leads': {
      id: '/_dashboard/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/linkedin': {
      id: '/_dashboard/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof DashboardLinkedinRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/outreach': {
      id: '/_dashboard/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof DashboardOutreachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tasks': {
      id: '/_dashboard/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardLinkedinRoute: typeof DashboardLinkedinRoute
  DashboardOutreachRoute: typeof DashboardOutreachRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardLinkedinRoute: DashboardLinkedinRoute,
  DashboardOutreachRoute: DashboardOutreachRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
