/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardAgentsRouteImport } from './routes/_dashboard.agents'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard.analytics'
import { Route as DashboardCampaignsRouteImport } from './routes/_dashboard.campaigns'
import { Route as DashboardClientsRouteImport } from './routes/_dashboard.clients'
import { Route as DashboardContentRouteImport } from './routes/_dashboard.content'
import { Route as DashboardCrmRouteImport } from './routes/_dashboard.crm'
import { Route as DashboardDistributionRouteImport } from './routes/_dashboard.distribution'
import { Route as DashboardExecutionRouteImport } from './routes/_dashboard.execution'
import { Route as DashboardIntegrationsRouteImport } from './routes/_dashboard.integrations'
import { Route as DashboardLeadsRouteImport } from './routes/_dashboard.leads'
import { Route as DashboardLinkedinRouteImport } from './routes/_dashboard.linkedin'
import { Route as DashboardNotificationsRouteImport } from './routes/_dashboard.notifications'
import { Route as DashboardOutreachRouteImport } from './routes/_dashboard.outreach'
import { Route as DashboardReportsRouteImport } from './routes/_dashboard.reports'
import { Route as DashboardResearchRouteImport } from './routes/_dashboard.research'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardTasksRouteImport } from './routes/_dashboard.tasks'
import { Route as DashboardVisibilityRouteImport } from './routes/_dashboard.visibility'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DebugSupabaseRouteImport } from './routes/debug.supabase'
import { Route as DashboardContentCalendarRouteImport } from './routes/_dashboard.content.calendar'
import { Route as DashboardContentLibraryRouteImport } from './routes/_dashboard.content.library'
import { Route as DashboardContentStrategyRouteImport } from './routes/_dashboard.content.strategy'
import { Route as DashboardResearchHistoryRouteImport } from './routes/_dashboard.research.history'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCrmRoute = DashboardCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDistributionRoute = DashboardDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExecutionRoute = DashboardExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinkedinRoute = DashboardLinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOutreachRoute = DashboardOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResearchRoute = DashboardResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVisibilityRoute = DashboardVisibilityRouteImport.update({
  id: '/visibility',
  path: '/visibility',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugSupabaseRoute = DebugSupabaseRouteImport.update({
  id: '/debug/supabase',
  path: '/debug/supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardContentCalendarRoute =
  DashboardContentCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => DashboardContentRoute,
  } as any)
const DashboardContentLibraryRoute = DashboardContentLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardContentRoute,
} as any)
const DashboardContentStrategyRoute =
  DashboardContentStrategyRouteImport.update({
    id: '/strategy',
    path: '/strategy',
    getParentRoute: () => DashboardContentRoute,
  } as any)
const DashboardResearchHistoryRoute =
  DashboardResearchHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => DashboardResearchRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agents': typeof DashboardAgentsRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/campaigns': typeof DashboardCampaignsRoute
  '/clients': typeof DashboardClientsRoute
  '/content': typeof DashboardContentRouteWithChildren
  '/crm': typeof DashboardCrmRoute
  '/distribution': typeof DashboardDistributionRoute
  '/execution': typeof DashboardExecutionRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/leads': typeof DashboardLeadsRoute
  '/linkedin': typeof DashboardLinkedinRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/outreach': typeof DashboardOutreachRoute
  '/reports': typeof DashboardReportsRoute
  '/research': typeof DashboardResearchRouteWithChildren
  '/settings': typeof DashboardSettingsRoute
  '/tasks': typeof DashboardTasksRoute
  '/visibility': typeof DashboardVisibilityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/debug/supabase': typeof DebugSupabaseRoute
  '/content/calendar': typeof DashboardContentCalendarRoute
  '/content/library': typeof DashboardContentLibraryRoute
  '/content/strategy': typeof DashboardContentStrategyRoute
  '/research/history': typeof DashboardResearchHistoryRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agents': typeof DashboardAgentsRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/campaigns': typeof DashboardCampaignsRoute
  '/clients': typeof DashboardClientsRoute
  '/content': typeof DashboardContentRouteWithChildren
  '/crm': typeof DashboardCrmRoute
  '/distribution': typeof DashboardDistributionRoute
  '/execution': typeof DashboardExecutionRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/leads': typeof DashboardLeadsRoute
  '/linkedin': typeof DashboardLinkedinRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/outreach': typeof DashboardOutreachRoute
  '/reports': typeof DashboardReportsRoute
  '/research': typeof DashboardResearchRouteWithChildren
  '/settings': typeof DashboardSettingsRoute
  '/tasks': typeof DashboardTasksRoute
  '/visibility': typeof DashboardVisibilityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/debug/supabase': typeof DebugSupabaseRoute
  '/': typeof DashboardIndexRoute
  '/content/calendar': typeof DashboardContentCalendarRoute
  '/content/library': typeof DashboardContentLibraryRoute
  '/content/strategy': typeof DashboardContentStrategyRoute
  '/research/history': typeof DashboardResearchHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_dashboard/agents': typeof DashboardAgentsRoute
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/_dashboard/campaigns': typeof DashboardCampaignsRoute
  '/_dashboard/clients': typeof DashboardClientsRoute
  '/_dashboard/content': typeof DashboardContentRouteWithChildren
  '/_dashboard/crm': typeof DashboardCrmRoute
  '/_dashboard/distribution': typeof DashboardDistributionRoute
  '/_dashboard/execution': typeof DashboardExecutionRoute
  '/_dashboard/integrations': typeof DashboardIntegrationsRoute
  '/_dashboard/leads': typeof DashboardLeadsRoute
  '/_dashboard/linkedin': typeof DashboardLinkedinRoute
  '/_dashboard/notifications': typeof DashboardNotificationsRoute
  '/_dashboard/outreach': typeof DashboardOutreachRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/research': typeof DashboardResearchRouteWithChildren
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/tasks': typeof DashboardTasksRoute
  '/_dashboard/visibility': typeof DashboardVisibilityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/debug/supabase': typeof DebugSupabaseRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/content/calendar': typeof DashboardContentCalendarRoute
  '/_dashboard/content/library': typeof DashboardContentLibraryRoute
  '/_dashboard/content/strategy': typeof DashboardContentStrategyRoute
  '/_dashboard/research/history': typeof DashboardResearchHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/agents'
    | '/analytics'
    | '/campaigns'
    | '/clients'
    | '/content'
    | '/crm'
    | '/distribution'
    | '/execution'
    | '/integrations'
    | '/leads'
    | '/linkedin'
    | '/notifications'
    | '/outreach'
    | '/reports'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/visibility'
    | '/auth/callback'
    | '/debug/supabase'
    | '/content/calendar'
    | '/content/library'
    | '/content/strategy'
    | '/research/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/agents'
    | '/analytics'
    | '/campaigns'
    | '/clients'
    | '/content'
    | '/crm'
    | '/distribution'
    | '/execution'
    | '/integrations'
    | '/leads'
    | '/linkedin'
    | '/notifications'
    | '/outreach'
    | '/reports'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/visibility'
    | '/auth/callback'
    | '/debug/supabase'
    | '/'
    | '/content/calendar'
    | '/content/library'
    | '/content/strategy'
    | '/research/history'
  id:
    | '__root__'
    | '/_dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_dashboard/agents'
    | '/_dashboard/analytics'
    | '/_dashboard/campaigns'
    | '/_dashboard/clients'
    | '/_dashboard/content'
    | '/_dashboard/crm'
    | '/_dashboard/distribution'
    | '/_dashboard/execution'
    | '/_dashboard/integrations'
    | '/_dashboard/leads'
    | '/_dashboard/linkedin'
    | '/_dashboard/notifications'
    | '/_dashboard/outreach'
    | '/_dashboard/reports'
    | '/_dashboard/research'
    | '/_dashboard/settings'
    | '/_dashboard/tasks'
    | '/_dashboard/visibility'
    | '/auth/callback'
    | '/debug/supabase'
    | '/_dashboard/'
    | '/_dashboard/content/calendar'
    | '/_dashboard/content/library'
    | '/_dashboard/content/strategy'
    | '/_dashboard/research/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DebugSupabaseRoute: typeof DebugSupabaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents': {
      id: '/_dashboard/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/campaigns': {
      id: '/_dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clients': {
      id: '/_dashboard/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content': {
      id: '/_dashboard/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/crm': {
      id: '/_dashboard/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof DashboardCrmRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/distribution': {
      id: '/_dashboard/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DashboardDistributionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/execution': {
      id: '/_dashboard/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof DashboardExecutionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/integrations': {
      id: '/_dashboard/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leads': {
      id: '/_dashboard/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/linkedin': {
      id: '/_dashboard/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof DashboardLinkedinRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/notifications': {
      id: '/_dashboard/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/outreach': {
      id: '/_dashboard/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof DashboardOutreachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/research': {
      id: '/_dashboard/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof DashboardResearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tasks': {
      id: '/_dashboard/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/visibility': {
      id: '/_dashboard/visibility'
      path: '/visibility'
      fullPath: '/visibility'
      preLoaderRoute: typeof DashboardVisibilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/supabase': {
      id: '/debug/supabase'
      path: '/debug/supabase'
      fullPath: '/debug/supabase'
      preLoaderRoute: typeof DebugSupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/content/calendar': {
      id: '/_dashboard/content/calendar'
      path: '/calendar'
      fullPath: '/content/calendar'
      preLoaderRoute: typeof DashboardContentCalendarRouteImport
      parentRoute: typeof DashboardContentRoute
    }
    '/_dashboard/content/library': {
      id: '/_dashboard/content/library'
      path: '/library'
      fullPath: '/content/library'
      preLoaderRoute: typeof DashboardContentLibraryRouteImport
      parentRoute: typeof DashboardContentRoute
    }
    '/_dashboard/content/strategy': {
      id: '/_dashboard/content/strategy'
      path: '/strategy'
      fullPath: '/content/strategy'
      preLoaderRoute: typeof DashboardContentStrategyRouteImport
      parentRoute: typeof DashboardContentRoute
    }
    '/_dashboard/research/history': {
      id: '/_dashboard/research/history'
      path: '/history'
      fullPath: '/research/history'
      preLoaderRoute: typeof DashboardResearchHistoryRouteImport
      parentRoute: typeof DashboardResearchRoute
    }
  }
}

interface DashboardContentRouteChildren {
  DashboardContentCalendarRoute: typeof DashboardContentCalendarRoute
  DashboardContentLibraryRoute: typeof DashboardContentLibraryRoute
  DashboardContentStrategyRoute: typeof DashboardContentStrategyRoute
}

const DashboardContentRouteChildren: DashboardContentRouteChildren = {
  DashboardContentCalendarRoute: DashboardContentCalendarRoute,
  DashboardContentLibraryRoute: DashboardContentLibraryRoute,
  DashboardContentStrategyRoute: DashboardContentStrategyRoute,
}

const DashboardContentRouteWithChildren =
  DashboardContentRoute._addFileChildren(DashboardContentRouteChildren)

interface DashboardResearchRouteChildren {
  DashboardResearchHistoryRoute: typeof DashboardResearchHistoryRoute
}

const DashboardResearchRouteChildren: DashboardResearchRouteChildren = {
  DashboardResearchHistoryRoute: DashboardResearchHistoryRoute,
}

const DashboardResearchRouteWithChildren =
  DashboardResearchRoute._addFileChildren(DashboardResearchRouteChildren)

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardContentRoute: typeof DashboardContentRouteWithChildren
  DashboardCrmRoute: typeof DashboardCrmRoute
  DashboardDistributionRoute: typeof DashboardDistributionRoute
  DashboardExecutionRoute: typeof DashboardExecutionRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardLinkedinRoute: typeof DashboardLinkedinRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOutreachRoute: typeof DashboardOutreachRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardResearchRoute: typeof DashboardResearchRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardVisibilityRoute: typeof DashboardVisibilityRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardContentRoute: DashboardContentRouteWithChildren,
  DashboardCrmRoute: DashboardCrmRoute,
  DashboardDistributionRoute: DashboardDistributionRoute,
  DashboardExecutionRoute: DashboardExecutionRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardLinkedinRoute: DashboardLinkedinRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOutreachRoute: DashboardOutreachRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardResearchRoute: DashboardResearchRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardVisibilityRoute: DashboardVisibilityRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DebugSupabaseRoute: DebugSupabaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
