-- ==============================================================================
-- Eminarc Growth OS — Growth Strategies Schema Migration
-- Migration: 20260805150000_growth_strategies_schema.sql
-- Description: Creates growth_strategies table for persisting 12-section AI strategic outputs.
-- ==============================================================================

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------------------------
-- GROWTH_STRATEGIES TABLE
-- Stores full 12-section strategic growth playbooks generated by AI agents.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.growth_strategies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  company_id UUID NULL REFERENCES public.companies(id) ON DELETE SET NULL,
  research_report_id UUID NULL REFERENCES public.research_reports(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('draft', 'generating', 'completed', 'failed')),
  executive_summary TEXT NOT NULL,
  icp JSONB NOT NULL DEFAULT '{}'::jsonb,
  buyer_personas JSONB NOT NULL DEFAULT '[]'::jsonb,
  positioning JSONB NOT NULL DEFAULT '{}'::jsonb,
  messaging_pillars JSONB NOT NULL DEFAULT '[]'::jsonb,
  value_proposition JSONB NOT NULL DEFAULT '{}'::jsonb,
  market_opportunities JSONB NOT NULL DEFAULT '[]'::jsonb,
  competitor_positioning JSONB NOT NULL DEFAULT '[]'::jsonb,
  channel_strategy JSONB NOT NULL DEFAULT '[]'::jsonb,
  growth_roadmap JSONB NOT NULL DEFAULT '[]'::jsonb,
  plan_30_60_90 JSONB NOT NULL DEFAULT '{}'::jsonb,
  success_metrics JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

-- Trigger for auto-updating updated_at on growth_strategies
CREATE TRIGGER update_growth_strategies_updated_at
BEFORE UPDATE ON public.growth_strategies
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Indexes for growth_strategies
CREATE INDEX IF NOT EXISTS idx_growth_strategies_workspace ON public.growth_strategies(workspace_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_growth_strategies_company ON public.growth_strategies(company_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_growth_strategies_status ON public.growth_strategies(status) WHERE deleted_at IS NULL;

-- ------------------------------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ------------------------------------------------------------------------------
ALTER TABLE public.growth_strategies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Growth strategies are viewable by workspace members"
ON public.growth_strategies FOR SELECT
USING (public.is_workspace_member(workspace_id) AND deleted_at IS NULL);

CREATE POLICY "Growth strategies can be created by workspace members"
ON public.growth_strategies FOR INSERT
WITH CHECK (public.is_workspace_member(workspace_id));

CREATE POLICY "Growth strategies can be updated by workspace members"
ON public.growth_strategies FOR UPDATE
USING (public.is_workspace_member(workspace_id))
WITH CHECK (public.is_workspace_member(workspace_id));

CREATE POLICY "Growth strategies can be deleted by workspace members"
ON public.growth_strategies FOR DELETE
USING (public.is_workspace_member(workspace_id));
